base_url = "https://xinuzo.github.io/diary"
title = "日記"
description = "just random nonsense"
author = "Rendi Adinata"

generate_feeds = true
feed_filenames = ["atom.xml"]
compile_sass = true
minify_html = false

[extra]
avatar = "/images/avatar.jpg"
