base_url = "https://xinuzo.github.io/wall"
title = "日記"
description = "hi, i learn to write here. "
author = "Rendi Adinata"

generate_feeds = true
feed_filenames = ["atom.xml"]
compile_sass = true
minify_html = false

[extra]
avatar = "/images/avatar.jpg"
